In [2]:
import numpy as np

In [3]:
type(np.array(["JATIN",1997,4]))

numpy.ndarray

In [4]:
np.array([1,2,3,4.])

array([1., 2., 3., 4.])

In [5]:
np.array([[1,23,3],[32,3,2]])

array([[ 1, 23,  3],
       [32,  3,  2]])

In [6]:
np.array([1,2,3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [7]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])

In [9]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [10]:
type(x)

numpy.ndarray

In [11]:
type(x[1][1])

numpy.int64

In [12]:
np.matrix(np.array([[1,2,3],[2,3,4]]))

matrix([[1, 2, 3],
        [2, 3, 4]])

In [13]:
l=[1,2,34,5,5,3]

In [14]:
type(l)

list

In [15]:
n=np.asarray(l)
n

array([ 1,  2, 34,  5,  5,  3])

In [16]:
type(n)

numpy.ndarray

In [17]:
a=np.array([1,2,3])

In [18]:
a

array([1, 2, 3])

In [19]:
a is a

True

In [20]:
issubclass(np.matrix,np.ndarray)

True

In [21]:
a=[1,2]
np.array(a)

array([1, 2])

In [22]:
np.asanyarray(a)

array([1, 2])

In [23]:
np.array(a,copy=True)

array([1, 2])

In [24]:
x=np.array([1,2,3])

In [25]:
x

array([1, 2, 3])

In [27]:
y=x

In [28]:
id(x)

1232649358592

In [29]:
id(y)

1232649358592

In [31]:
z=np.copy(x)

In [32]:
z

array([1, 2, 3])

In [33]:
id(z)

1232649327120

In [34]:
z[0]=22

In [35]:
z

array([22,  2,  3])

In [36]:
x

array([1, 2, 3])

In [37]:
y[0]=809

In [38]:
x

array([809,   2,   3])

In [41]:
np.fromfunction(lambda i,j:i==j,(3,4),dtype=int)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [62]:
iterable=(x*x for x in range(5))

In [63]:
iterable

<generator object <genexpr> at 0x0000011EFFA220C8>

In [64]:
np.fromiter(iterable,int) #execute above two stmnts if not showing

array([ 0,  1,  4,  9, 16])

In [68]:
np.fromstring("1122,47658",sep=",",dtype=int)

array([ 1122, 47658])

In [71]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [72]:
x1

array([1, 2, 3, 4])

In [73]:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')

In [74]:
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [78]:
# import numpy 
import numpy as np 

# using numpy.core.fromarrays() method 
li1 = np.array([101, 102, 103, 104]) 
li2 = np.array(['Jitender', 'Purnima', 'Ruhi', 'Varun']) 
li3 = np.array([21, 22, 12, 35]) 

gfg = np.core.records.fromarrays([li1, li2, li3], 
					names ='Rollno, Name, Age') 

for i in gfg:
    print(i)


(101, 'Jitender', 21)
(102, 'Purnima', 22)
(103, 'Ruhi', 12)
(104, 'Varun', 35)


In [79]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [80]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [81]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [82]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [83]:
print(type(np.arange(5,16)))

<class 'numpy.ndarray'>


In [84]:
list(range(5,15,2))

[5, 7, 9, 11, 13]

In [85]:
print(np.arange(0,11,2.5))

[ 0.   2.5  5.   7.5 10. ]


In [89]:
np.arange(5,-1,-5)

array([5, 0])

In [90]:
np.linspace(1,2,52)

array([1.        , 1.01960784, 1.03921569, 1.05882353, 1.07843137,
       1.09803922, 1.11764706, 1.1372549 , 1.15686275, 1.17647059,
       1.19607843, 1.21568627, 1.23529412, 1.25490196, 1.2745098 ,
       1.29411765, 1.31372549, 1.33333333, 1.35294118, 1.37254902,
       1.39215686, 1.41176471, 1.43137255, 1.45098039, 1.47058824,
       1.49019608, 1.50980392, 1.52941176, 1.54901961, 1.56862745,
       1.58823529, 1.60784314, 1.62745098, 1.64705882, 1.66666667,
       1.68627451, 1.70588235, 1.7254902 , 1.74509804, 1.76470588,
       1.78431373, 1.80392157, 1.82352941, 1.84313725, 1.8627451 ,
       1.88235294, 1.90196078, 1.92156863, 1.94117647, 1.96078431,
       1.98039216, 2.        ])

In [92]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [94]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [101]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
np.ones((2,3,4))+4*6

array([[[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]],

       [[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]]])

In [105]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [107]:
np.arange(3,dtype=float)

array([0., 1., 2.])

In [109]:
np.arange(3,7,2)

array([3, 5])

In [111]:
np.linspace(2,3,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [113]:
np.linspace(2,3,num=9,retstep=True)#five stepsize

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [114]:
np.linspace(2,3,num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [2]:
import numpy as np
np.logspace(2,3,num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [24]:
x=np.arange(16).reshape(4,-1)

In [30]:
x

array([[ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  6,  0],
       [ 0,  0,  0,  0, 11],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [37]:
x=np.diag(x,k=6)

In [38]:
x

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [40]:
np.diagflat([[1,2],[3,4]],2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [46]:
np.tri(2,4,dtype=int)

array([[1, 0, 0, 0],
       [1, 1, 0, 0]])

In [47]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [54]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [55]:
np.random.rand(2,3)

array([[0.23887365, 0.06879522, 0.15951131],
       [0.90128686, 0.55972488, 0.08294159]])

In [56]:
np.random.randn(2,3)

array([[ 1.57092884, -1.40438073, -0.67029106],
       [ 0.51207301,  2.01741021, -2.20434219]])

In [57]:
np.random.randint(1,50,(4,3))

array([[13, 15, 10],
       [24, 29,  9],
       [ 8, 31, 21],
       [48, 31, 45]])

In [59]:
a=np.arange(0,11)

In [60]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
a[7]

7

In [62]:
a[3:9]

array([3, 4, 5, 6, 7, 8])

In [64]:
a[-1:7:-1]

array([10,  9,  8])

In [70]:
a[-1:-6:2]

array([], dtype=int32)

In [71]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
a[[2,3,4]]

array([2, 3, 4])

In [76]:
m=np.array(np.random.randint(10,100,15)).reshape(3,5)

In [77]:
m

array([[72, 12, 58, 92, 37],
       [12, 97, 90, 44, 73],
       [51, 11, 73, 94, 79]])

In [79]:
m[[1,2],3:5]

array([[44, 73],
       [94, 79]])

m[1]

In [80]:
m[1]

array([12, 97, 90, 44, 73])

In [81]:
m[1][1]

97

In [82]:
m[2][4]

79

In [83]:
m[2]

array([51, 11, 73, 94, 79])

In [84]:
m[:,4]

array([37, 73, 79])

In [85]:
m>40

array([[ True, False,  True,  True, False],
       [False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [86]:
m[m>40]

array([72, 58, 92, 97, 90, 44, 73, 51, 73, 94, 79])