In [1]:
mylist=[1,23]

In [2]:
import numpy as np

In [3]:
np.array(mylist)

array([ 1, 23])

In [4]:
my_mat=[[1,23,3],[2,334,4],[33,44,3]]

In [5]:
np.array(my_mat)

array([[  1,  23,   3],
       [  2, 334,   4],
       [ 33,  44,   3]])

In [6]:
np.arange

<function numpy.arange>

In [8]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5,7,2)

array([[[0.21549018, 0.12221234],
        [0.14846191, 0.92838575],
        [0.79015897, 0.96520475],
        [0.1957068 , 0.56278295],
        [0.75632284, 0.22618072],
        [0.00949466, 0.6745162 ],
        [0.49709422, 0.28727076]],

       [[0.46454761, 0.2197034 ],
        [0.22943555, 0.32417557],
        [0.30174143, 0.08517911],
        [0.25987438, 0.43201087],
        [0.40095289, 0.24722392],
        [0.5032048 , 0.34234291],
        [0.93032189, 0.31715349]],

       [[0.76839416, 0.72156278],
        [0.50156627, 0.93379546],
        [0.31488804, 0.61205901],
        [0.32723112, 0.74251104],
        [0.69294381, 0.01933104],
        [0.31455414, 0.79104324],
        [0.30537351, 0.65634534]],

       [[0.18752938, 0.08368306],
        [0.31452345, 0.65057726],
        [0.53880172, 0.58421204],
        [0.11598476, 0.41904352],
        [0.10959412, 0.97028799],
        [0.79280482, 0.29346891],
        [0.52795271, 0.94368478]],

       [[0.11679928, 0.01136924],
      

In [23]:
np.random.randn(3,3)

array([[-3.27217848e-01, -6.26976305e-01,  1.91507809e+00],
       [-1.37454735e+00, -4.64320439e-01, -5.74324517e-01],
       [-8.25688353e-04, -4.97322243e-01, -1.23739875e+00]])

In [27]:
np.random.randint(1,100,4)

array([63, 35, 55, 62])

In [28]:
arr=np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr=np.random.randint(0,25,5)

In [31]:
ranarr

array([15, 12, 18,  0,  2])

In [32]:
ranarr

array([15, 12, 18,  0,  2])

In [33]:
ranarr.max()

18

In [34]:
ranarr.min()

0

In [35]:
ranarr.argmax()

2

In [36]:
ranarr.argmin()

3

In [37]:
arr.shape

(25,)

In [38]:
ranarr.shape

(5,)

In [39]:
ranarr.dtype

dtype('int32')