In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:4]

array([1, 2, 3])

In [6]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[6:8]

array([6, 7])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5]=111

In [12]:
arr

array([111, 111, 111, 111, 111,   5,   6,   7,   8,   9,  10])

In [13]:
arr=np.arange(0,11)

In [14]:
soa=arr[:]

In [17]:
ac=arr.copy()

In [18]:
ac

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
ac[:]=111

In [20]:
ac

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a2d=np.array([[1,2,2],[22,3,2],[6,7,4]])

In [23]:
a2d

array([[ 1,  2,  2],
       [22,  3,  2],
       [ 6,  7,  4]])

In [24]:
a2d[0,0]

1

In [25]:
a2d[2,1]

7

In [26]:
a2d[0][0]

1

In [27]:
a2d

array([[ 1,  2,  2],
       [22,  3,  2],
       [ 6,  7,  4]])

In [30]:
a2d[1:2,0:2]

array([[22,  3]])

In [31]:
#conditional_selection

In [32]:
arr=np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr=arr>5

In [39]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr<3]

array([1, 2])

In [43]:
arr<3

array([ True,  True, False, False, False, False, False, False, False,
       False])